function plot_neutrality_comparison(mean_hamming_distance_max_vp1_L500, mean_hamming_distance_max_vp1_L1000, ...
    mean_hamming_distance_max_p24_L500, mean_hamming_distance_max_p24_L1000, ...
    mean_hamming_distance_max_epsilon_gp160_L500, mean_hamming_distance_max_epsilon_gp160_L1000)

run startup.m

epsilon = [.1 .3 .5 .8 3];
figure;
loglog(epsilon,mean_hamming_distance_max_vp1_L500,'Color',blue,'LineWidth',2)
hold on
loglog(epsilon,mean_hamming_distance_max_p24_L500,'Color',red,'LineWidth',2)
loglog(epsilon,mean_hamming_distance_max_epsilon_gp160_L500,'Color',purple,'LineWidth',2)
loglog(epsilon,mean_hamming_distance_max_vp1_L1000,'--','Color',blue,'LineWidth',2)
loglog(epsilon,mean_hamming_distance_max_p24_L1000,'--','Color',red,'LineWidth',2)
loglog(epsilon,mean_hamming_distance_max_epsilon_gp160_L1000,'--','Color',purple,'LineWidth',2)

xlabel('Acceptable change in fitness, \epsilon','interpreter','tex')
ylabel('Neutrality')

set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'XColor'      , [.1 .1 .1], ...
  'YColor'      , [.1 .1 .1], ...
  'YTick'       , [1e-3 1e-2 1e-1 1 10], ...
  'XTick'       , [1e-1 1], ...
  'LineWidth'   , 1        );

xlim([1e-1 1])
ylim([1e-3 2])    