function plot_three_point_correlations(p3_data,p3_sampler,color,markersize)

figure;
plot(p3_data,p3_sampler,'o','MarkerFaceColor',color,'MarkerEdgeColor',color,'MarkerSize',markersize)
hold on;
max_value = max(max(p3_data,p3_sampler));
plot(0:max_value/20:max_value,0:max_value/20:max_value,'k')
xlabel('Triple mutant probability (MSA)')
ylabel('Triple mutant probability')
% [r,pval] = corr(p3_data.',p3_sampler.','type','pearson','tail','right')
% [number,exponent] = convert_exp_power10(pval);
% text(0.175,0.06,sprintf('$$\\rho = %0.4f$$',r),'interpreter','latex')
% text(0.175,0.04,sprintf('$$p < 10^{-100}$$'),'interpreter','latex')  
xlim([0 0.25])
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'XColor'      , [.1 .1 .1], ...
  'YColor'      , [.1 .1 .1], ...
  'YTick'       , [0:0.05:0.3],...
  'XTick'       , [0:0.05:0.3],...
  'LineWidth'   , .5        );