function plot_autocorrelation_comparison(ak_vp1_D5,ak_vp1_D30,...
    ak_p24_D5,ak_p24_D30,ak_gp160_D5,ak_gp160_D30)

run startup.m

no_of_steps = 50;
figure
plot(1:no_of_steps,real(ak_vp1_D5),'-','Color',blue,'LineWidth',2)
hold on
plot(1:no_of_steps,real(ak_p24_D5),'-','Color',red,'LineWidth',2)
plot(1:no_of_steps,real(ak_gp160_D5),'-','Color',purple,'LineWidth',2)
plot(1:no_of_steps,real(ak_vp1_D30),'--','Color',blue,'LineWidth',2)
plot(1:no_of_steps,real(ak_p24_D30),'--','Color',red,'LineWidth',2)
plot(1:no_of_steps,real(ak_gp160_D30),'--','Color',purple,'LineWidth',2)
ylabel('Autocorrelation')
xlabel('Number of random-walk steps, k')
legend('vp1','p24','gp160','Location','SouthWest')
ylim([0.1 1])
legend boxoff

set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'XColor'      , [.1 .1 .1], ...
  'YColor'      , [.1 .1 .1], ...
  'YTick'       , 0:0.2:1, ...
  'XTick'       , 0:10:50, ...
  'LineWidth'   , 1        );