function post_proc_fig

set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.01 .01] , ...%'XMinorTick'  , 'off'      , ...'YMinorTick'  , 'on'      , ...
    'XColor'      , [.1 .1 .1], ...
    'YColor'      , [.1 .1 .1], ...%    'YTick'       , 0:5:30,...    
    'LineWidth'   , .5        );